// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rubinho_s_Bar___Tchelos.Infra.Orm.MóduloCompartilhado;

#nullable disable

namespace Rubinho_s_Bar___Tchelos.Infra.Migrations
{
    [DbContext(typeof(BotecoDbContext))]
    [Migration("20240708185117_Add Mesas")]
    partial class AddMesas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rubinho_s_Bar___Tchelos.Dominio.MóduloMesa.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroDaMesa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TBMesa", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
